//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class EJECUCION_TAREA
    {
        public EJECUCION_TAREA()
        {
            this.PROBLEMA_EJECUCION = new HashSet<PROBLEMA_EJECUCION>();
        }
    
        public short IDEJTAREA { get; set; }
        public System.DateTime FECHAINCICIO { get; set; }
        public System.DateTime FECHATERMINO { get; set; }
        public string OBSERVACION { get; set; }
        public short FLUJO_IDFLUJO { get; set; }
        public short ESTADO_EJECUCION_IDESTADO { get; set; }
    
        public virtual ESTADO_EJECUCION ESTADO_EJECUCION { get; set; }
        public virtual FLUJO FLUJO { get; set; }
        public virtual ICollection<PROBLEMA_EJECUCION> PROBLEMA_EJECUCION { get; set; }
    }
}
