//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class EJECUCION
    {
        public EJECUCION()
        {
            this.FLUJO_TAREA = new HashSet<FLUJO_TAREA>();
            this.INCIDENCIA = new HashSet<INCIDENCIA>();
        }
    
        public short IDEJECUCION { get; set; }
        public Nullable<System.DateTime> FECHAINICIO { get; set; }
        public System.DateTime FECHATERMINO { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual ICollection<FLUJO_TAREA> FLUJO_TAREA { get; set; }
        public virtual ICollection<INCIDENCIA> INCIDENCIA { get; set; }
    }
}
