//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        public EMPRESA()
        {
            this.UNIDAD = new HashSet<UNIDAD>();
        }
    
        public short IDEMPRESA { get; set; }
        public int RUTEMPRESA { get; set; }
        public string DVEMPRESA { get; set; }
        public string NOMBREEMPRESA { get; set; }
        public string DIRECCION { get; set; }
    
        public virtual ICollection<UNIDAD> UNIDAD { get; set; }
    }
}
