//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_EJECUCION
    {
        public ESTADO_EJECUCION()
        {
            this.EJECUCION_TAREA = new HashSet<EJECUCION_TAREA>();
        }
    
        public short IDESTADO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<EJECUCION_TAREA> EJECUCION_TAREA { get; set; }
    }
}
