//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLUJO
    {
        public FLUJO()
        {
            this.EJECUCION_TAREA = new HashSet<EJECUCION_TAREA>();
            this.FLUJO_TAREA = new HashSet<FLUJO_TAREA>();
        }
    
        public short IDFLUJO { get; set; }
        public string NOMBREFLUJO { get; set; }
        public string OBSERVACIONFLUJO { get; set; }
        public System.DateTime FECHACREACION { get; set; }
        public short FLUJO_ESTADO_IDFESTADO { get; set; }
    
        public virtual ICollection<EJECUCION_TAREA> EJECUCION_TAREA { get; set; }
        public virtual FLUJO_ESTADO FLUJO_ESTADO { get; set; }
        public virtual ICollection<FLUJO_TAREA> FLUJO_TAREA { get; set; }
    }
}
