//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLUJO_ESTADO
    {
        public FLUJO_ESTADO()
        {
            this.FLUJO = new HashSet<FLUJO>();
        }
    
        public short IDFESTADO { get; set; }
        public string DECRIPCIONFLUJO { get; set; }
    
        public virtual ICollection<FLUJO> FLUJO { get; set; }
    }
}
