//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLUJO_TAREA
    {
        public int IDFTAREA { get; set; }
        public System.DateTime FECHA { get; set; }
        public int TAREA_IDTAREA { get; set; }
        public short FLUJO_IDFLUJO { get; set; }
    
        public virtual FLUJO FLUJO { get; set; }
        public virtual TAREA TAREA { get; set; }
    }
}
