//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO
    {
        public FUNCIONARIO()
        {
            this.FUNCIONARIO_TAREA = new HashSet<FUNCIONARIO_TAREA>();
            this.USUARIO_FUNCIONARIO = new HashSet<USUARIO_FUNCIONARIO>();
        }
    
        public short IDFUNCIONARIO { get; set; }
        public long RUT { get; set; }
        public string DV { get; set; }
        public string PNOMBRE { get; set; }
        public string SNOMBRE { get; set; }
        public string APATERNO { get; set; }
        public string AMATERNO { get; set; }
        public int TELEFONO { get; set; }
        public string CORREO { get; set; }
        public string DIRECCION { get; set; }
        public short UNIDAD_IDUNIDAD { get; set; }
    
        public virtual ICollection<FUNCIONARIO_TAREA> FUNCIONARIO_TAREA { get; set; }
        public virtual UNIDAD UNIDAD { get; set; }
        public virtual ICollection<USUARIO_FUNCIONARIO> USUARIO_FUNCIONARIO { get; set; }
    }
}
