//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENCIA
    {
        public short IDINCIDENCIA { get; set; }
        public string OBSERVACION { get; set; }
        public System.DateTime FECHA { get; set; }
        public short EJECUCION_IDEJECUCION { get; set; }
    
        public virtual EJECUCION EJECUCION { get; set; }
    }
}
