//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class JUSTIFICACION_TAREA
    {
        public int IDJUSTIFICACION { get; set; }
        public string OBSERVACION { get; set; }
        public System.DateTime FECHAJUSTIFICACION { get; set; }
        public short IDFUNCIONARIO { get; set; }
        public short FUNCIONARIO_TAREA_IDFUTAREA { get; set; }
    
        public virtual FUNCIONARIO_TAREA FUNCIONARIO_TAREA { get; set; }
    }
}
