//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesPro : DbContext
    {
        public EntitiesPro()
            : base("name=EntitiesPro")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EJECUCION_TAREA> EJECUCION_TAREA { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<ESTADO_EJECUCION> ESTADO_EJECUCION { get; set; }
        public DbSet<ESTADO_SOLUCION> ESTADO_SOLUCION { get; set; }
        public DbSet<ESTADO_TAREA> ESTADO_TAREA { get; set; }
        public DbSet<FLUJO> FLUJO { get; set; }
        public DbSet<FLUJO_ESTADO> FLUJO_ESTADO { get; set; }
        public DbSet<FLUJO_TAREA> FLUJO_TAREA { get; set; }
        public DbSet<FUNCIONARIO> FUNCIONARIO { get; set; }
        public DbSet<FUNCIONARIO_TAREA> FUNCIONARIO_TAREA { get; set; }
        public DbSet<JUSTIFICACION_TAREA> JUSTIFICACION_TAREA { get; set; }
        public DbSet<PROBLEMA_EJECUCION> PROBLEMA_EJECUCION { get; set; }
        public DbSet<RESOLUCION_PROBLEMA> RESOLUCION_PROBLEMA { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<TAREA> TAREA { get; set; }
        public DbSet<UNIDAD> UNIDAD { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<USUARIO_FUNCIONARIO> USUARIO_FUNCIONARIO { get; set; }
    
        public virtual int EJECUCION_TAREA_DEL(Nullable<decimal> p_IDEJTAREA)
        {
            var p_IDEJTAREAParameter = p_IDEJTAREA.HasValue ?
                new ObjectParameter("P_IDEJTAREA", p_IDEJTAREA) :
                new ObjectParameter("P_IDEJTAREA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EJECUCION_TAREA_DEL", p_IDEJTAREAParameter);
        }
    
        public virtual int EJECUCION_TAREA_INS(Nullable<decimal> p_IDEJTAREA, Nullable<decimal> p_FLUJO_IDFLUJO, Nullable<decimal> p_ESTADO_EJECUCION_IDESTADO, string p_OBSERVACION, Nullable<System.DateTime> p_FECHATERMINO, Nullable<System.DateTime> p_FECHAINCICIO)
        {
            var p_IDEJTAREAParameter = p_IDEJTAREA.HasValue ?
                new ObjectParameter("P_IDEJTAREA", p_IDEJTAREA) :
                new ObjectParameter("P_IDEJTAREA", typeof(decimal));
    
            var p_FLUJO_IDFLUJOParameter = p_FLUJO_IDFLUJO.HasValue ?
                new ObjectParameter("P_FLUJO_IDFLUJO", p_FLUJO_IDFLUJO) :
                new ObjectParameter("P_FLUJO_IDFLUJO", typeof(decimal));
    
            var p_ESTADO_EJECUCION_IDESTADOParameter = p_ESTADO_EJECUCION_IDESTADO.HasValue ?
                new ObjectParameter("P_ESTADO_EJECUCION_IDESTADO", p_ESTADO_EJECUCION_IDESTADO) :
                new ObjectParameter("P_ESTADO_EJECUCION_IDESTADO", typeof(decimal));
    
            var p_OBSERVACIONParameter = p_OBSERVACION != null ?
                new ObjectParameter("P_OBSERVACION", p_OBSERVACION) :
                new ObjectParameter("P_OBSERVACION", typeof(string));
    
            var p_FECHATERMINOParameter = p_FECHATERMINO.HasValue ?
                new ObjectParameter("P_FECHATERMINO", p_FECHATERMINO) :
                new ObjectParameter("P_FECHATERMINO", typeof(System.DateTime));
    
            var p_FECHAINCICIOParameter = p_FECHAINCICIO.HasValue ?
                new ObjectParameter("P_FECHAINCICIO", p_FECHAINCICIO) :
                new ObjectParameter("P_FECHAINCICIO", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EJECUCION_TAREA_INS", p_IDEJTAREAParameter, p_FLUJO_IDFLUJOParameter, p_ESTADO_EJECUCION_IDESTADOParameter, p_OBSERVACIONParameter, p_FECHATERMINOParameter, p_FECHAINCICIOParameter);
        }
    
        public virtual int EJECUCION_TAREA_UPD(Nullable<decimal> p_IDEJTAREA, Nullable<decimal> p_FLUJO_IDFLUJO, Nullable<decimal> p_ESTADO_EJECUCION_IDESTADO, string p_OBSERVACION, Nullable<System.DateTime> p_FECHATERMINO, Nullable<System.DateTime> p_FECHAINCICIO)
        {
            var p_IDEJTAREAParameter = p_IDEJTAREA.HasValue ?
                new ObjectParameter("P_IDEJTAREA", p_IDEJTAREA) :
                new ObjectParameter("P_IDEJTAREA", typeof(decimal));
    
            var p_FLUJO_IDFLUJOParameter = p_FLUJO_IDFLUJO.HasValue ?
                new ObjectParameter("P_FLUJO_IDFLUJO", p_FLUJO_IDFLUJO) :
                new ObjectParameter("P_FLUJO_IDFLUJO", typeof(decimal));
    
            var p_ESTADO_EJECUCION_IDESTADOParameter = p_ESTADO_EJECUCION_IDESTADO.HasValue ?
                new ObjectParameter("P_ESTADO_EJECUCION_IDESTADO", p_ESTADO_EJECUCION_IDESTADO) :
                new ObjectParameter("P_ESTADO_EJECUCION_IDESTADO", typeof(decimal));
    
            var p_OBSERVACIONParameter = p_OBSERVACION != null ?
                new ObjectParameter("P_OBSERVACION", p_OBSERVACION) :
                new ObjectParameter("P_OBSERVACION", typeof(string));
    
            var p_FECHATERMINOParameter = p_FECHATERMINO.HasValue ?
                new ObjectParameter("P_FECHATERMINO", p_FECHATERMINO) :
                new ObjectParameter("P_FECHATERMINO", typeof(System.DateTime));
    
            var p_FECHAINCICIOParameter = p_FECHAINCICIO.HasValue ?
                new ObjectParameter("P_FECHAINCICIO", p_FECHAINCICIO) :
                new ObjectParameter("P_FECHAINCICIO", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EJECUCION_TAREA_UPD", p_IDEJTAREAParameter, p_FLUJO_IDFLUJOParameter, p_ESTADO_EJECUCION_IDESTADOParameter, p_OBSERVACIONParameter, p_FECHATERMINOParameter, p_FECHAINCICIOParameter);
        }
    
        public virtual int EMPRESA_DEL(Nullable<decimal> p_IDEMPRESA, Nullable<decimal> p_RUTEMPRESA)
        {
            var p_IDEMPRESAParameter = p_IDEMPRESA.HasValue ?
                new ObjectParameter("P_IDEMPRESA", p_IDEMPRESA) :
                new ObjectParameter("P_IDEMPRESA", typeof(decimal));
    
            var p_RUTEMPRESAParameter = p_RUTEMPRESA.HasValue ?
                new ObjectParameter("P_RUTEMPRESA", p_RUTEMPRESA) :
                new ObjectParameter("P_RUTEMPRESA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EMPRESA_DEL", p_IDEMPRESAParameter, p_RUTEMPRESAParameter);
        }
    
        public virtual int EMPRESA_INS(string p_DIRECCION, string p_DVEMPRESA, string p_NOMBREEMPRESA, Nullable<decimal> p_IDEMPRESA, Nullable<decimal> p_RUTEMPRESA)
        {
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_DVEMPRESAParameter = p_DVEMPRESA != null ?
                new ObjectParameter("P_DVEMPRESA", p_DVEMPRESA) :
                new ObjectParameter("P_DVEMPRESA", typeof(string));
    
            var p_NOMBREEMPRESAParameter = p_NOMBREEMPRESA != null ?
                new ObjectParameter("P_NOMBREEMPRESA", p_NOMBREEMPRESA) :
                new ObjectParameter("P_NOMBREEMPRESA", typeof(string));
    
            var p_IDEMPRESAParameter = p_IDEMPRESA.HasValue ?
                new ObjectParameter("P_IDEMPRESA", p_IDEMPRESA) :
                new ObjectParameter("P_IDEMPRESA", typeof(decimal));
    
            var p_RUTEMPRESAParameter = p_RUTEMPRESA.HasValue ?
                new ObjectParameter("P_RUTEMPRESA", p_RUTEMPRESA) :
                new ObjectParameter("P_RUTEMPRESA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EMPRESA_INS", p_DIRECCIONParameter, p_DVEMPRESAParameter, p_NOMBREEMPRESAParameter, p_IDEMPRESAParameter, p_RUTEMPRESAParameter);
        }
    
        public virtual int EMPRESA_UPD(string p_DIRECCION, string p_DVEMPRESA, string p_NOMBREEMPRESA, Nullable<decimal> p_IDEMPRESA, Nullable<decimal> p_RUTEMPRESA)
        {
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_DVEMPRESAParameter = p_DVEMPRESA != null ?
                new ObjectParameter("P_DVEMPRESA", p_DVEMPRESA) :
                new ObjectParameter("P_DVEMPRESA", typeof(string));
    
            var p_NOMBREEMPRESAParameter = p_NOMBREEMPRESA != null ?
                new ObjectParameter("P_NOMBREEMPRESA", p_NOMBREEMPRESA) :
                new ObjectParameter("P_NOMBREEMPRESA", typeof(string));
    
            var p_IDEMPRESAParameter = p_IDEMPRESA.HasValue ?
                new ObjectParameter("P_IDEMPRESA", p_IDEMPRESA) :
                new ObjectParameter("P_IDEMPRESA", typeof(decimal));
    
            var p_RUTEMPRESAParameter = p_RUTEMPRESA.HasValue ?
                new ObjectParameter("P_RUTEMPRESA", p_RUTEMPRESA) :
                new ObjectParameter("P_RUTEMPRESA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EMPRESA_UPD", p_DIRECCIONParameter, p_DVEMPRESAParameter, p_NOMBREEMPRESAParameter, p_IDEMPRESAParameter, p_RUTEMPRESAParameter);
        }
    
        public virtual int ESTADO_EJECUCION_DEL(Nullable<decimal> p_IDESTADO)
        {
            var p_IDESTADOParameter = p_IDESTADO.HasValue ?
                new ObjectParameter("P_IDESTADO", p_IDESTADO) :
                new ObjectParameter("P_IDESTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ESTADO_EJECUCION_DEL", p_IDESTADOParameter);
        }
    
        public virtual int ESTADO_EJECUCION_INS(Nullable<decimal> p_IDESTADO, string p_DESCRIPCION)
        {
            var p_IDESTADOParameter = p_IDESTADO.HasValue ?
                new ObjectParameter("P_IDESTADO", p_IDESTADO) :
                new ObjectParameter("P_IDESTADO", typeof(decimal));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ESTADO_EJECUCION_INS", p_IDESTADOParameter, p_DESCRIPCIONParameter);
        }
    
        public virtual int ESTADO_EJECUCION_UPD(Nullable<decimal> p_IDESTADO, string p_DESCRIPCION)
        {
            var p_IDESTADOParameter = p_IDESTADO.HasValue ?
                new ObjectParameter("P_IDESTADO", p_IDESTADO) :
                new ObjectParameter("P_IDESTADO", typeof(decimal));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ESTADO_EJECUCION_UPD", p_IDESTADOParameter, p_DESCRIPCIONParameter);
        }
    
        public virtual int ESTADO_SOLUCION_DEL(Nullable<decimal> p_ESOLUCION_ID)
        {
            var p_ESOLUCION_IDParameter = p_ESOLUCION_ID.HasValue ?
                new ObjectParameter("P_ESOLUCION_ID", p_ESOLUCION_ID) :
                new ObjectParameter("P_ESOLUCION_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ESTADO_SOLUCION_DEL", p_ESOLUCION_IDParameter);
        }
    
        public virtual int ESTADO_SOLUCION_INS(Nullable<decimal> p_IDESOLUCION, Nullable<decimal> p_ESOLUCION_ID, string p_DESCRIPCION)
        {
            var p_IDESOLUCIONParameter = p_IDESOLUCION.HasValue ?
                new ObjectParameter("P_IDESOLUCION", p_IDESOLUCION) :
                new ObjectParameter("P_IDESOLUCION", typeof(decimal));
    
            var p_ESOLUCION_IDParameter = p_ESOLUCION_ID.HasValue ?
                new ObjectParameter("P_ESOLUCION_ID", p_ESOLUCION_ID) :
                new ObjectParameter("P_ESOLUCION_ID", typeof(decimal));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ESTADO_SOLUCION_INS", p_IDESOLUCIONParameter, p_ESOLUCION_IDParameter, p_DESCRIPCIONParameter);
        }
    
        public virtual int ESTADO_SOLUCION_UPD(Nullable<decimal> p_IDESOLUCION, Nullable<decimal> p_ESOLUCION_ID, string p_DESCRIPCION)
        {
            var p_IDESOLUCIONParameter = p_IDESOLUCION.HasValue ?
                new ObjectParameter("P_IDESOLUCION", p_IDESOLUCION) :
                new ObjectParameter("P_IDESOLUCION", typeof(decimal));
    
            var p_ESOLUCION_IDParameter = p_ESOLUCION_ID.HasValue ?
                new ObjectParameter("P_ESOLUCION_ID", p_ESOLUCION_ID) :
                new ObjectParameter("P_ESOLUCION_ID", typeof(decimal));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ESTADO_SOLUCION_UPD", p_IDESOLUCIONParameter, p_ESOLUCION_IDParameter, p_DESCRIPCIONParameter);
        }
    
        public virtual int ESTADO_TAREA_DEL(Nullable<decimal> p_IDTAREA)
        {
            var p_IDTAREAParameter = p_IDTAREA.HasValue ?
                new ObjectParameter("P_IDTAREA", p_IDTAREA) :
                new ObjectParameter("P_IDTAREA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ESTADO_TAREA_DEL", p_IDTAREAParameter);
        }
    
        public virtual int ESTADO_TAREA_INS(Nullable<decimal> p_IDTAREA, string p_DESCRIPCIONESTADOTAREA)
        {
            var p_IDTAREAParameter = p_IDTAREA.HasValue ?
                new ObjectParameter("P_IDTAREA", p_IDTAREA) :
                new ObjectParameter("P_IDTAREA", typeof(decimal));
    
            var p_DESCRIPCIONESTADOTAREAParameter = p_DESCRIPCIONESTADOTAREA != null ?
                new ObjectParameter("P_DESCRIPCIONESTADOTAREA", p_DESCRIPCIONESTADOTAREA) :
                new ObjectParameter("P_DESCRIPCIONESTADOTAREA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ESTADO_TAREA_INS", p_IDTAREAParameter, p_DESCRIPCIONESTADOTAREAParameter);
        }
    
        public virtual int ESTADO_TAREA_UPD(Nullable<decimal> p_IDTAREA, string p_DESCRIPCIONESTADOTAREA)
        {
            var p_IDTAREAParameter = p_IDTAREA.HasValue ?
                new ObjectParameter("P_IDTAREA", p_IDTAREA) :
                new ObjectParameter("P_IDTAREA", typeof(decimal));
    
            var p_DESCRIPCIONESTADOTAREAParameter = p_DESCRIPCIONESTADOTAREA != null ?
                new ObjectParameter("P_DESCRIPCIONESTADOTAREA", p_DESCRIPCIONESTADOTAREA) :
                new ObjectParameter("P_DESCRIPCIONESTADOTAREA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ESTADO_TAREA_UPD", p_IDTAREAParameter, p_DESCRIPCIONESTADOTAREAParameter);
        }
    
        public virtual int FLUJO_ESTADO_DEL(Nullable<decimal> p_IDFESTADO)
        {
            var p_IDFESTADOParameter = p_IDFESTADO.HasValue ?
                new ObjectParameter("P_IDFESTADO", p_IDFESTADO) :
                new ObjectParameter("P_IDFESTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FLUJO_ESTADO_DEL", p_IDFESTADOParameter);
        }
    
        public virtual int FLUJO_ESTADO_INS(string p_DECRIPCIONFLUJO, Nullable<decimal> p_IDFESTADO)
        {
            var p_DECRIPCIONFLUJOParameter = p_DECRIPCIONFLUJO != null ?
                new ObjectParameter("P_DECRIPCIONFLUJO", p_DECRIPCIONFLUJO) :
                new ObjectParameter("P_DECRIPCIONFLUJO", typeof(string));
    
            var p_IDFESTADOParameter = p_IDFESTADO.HasValue ?
                new ObjectParameter("P_IDFESTADO", p_IDFESTADO) :
                new ObjectParameter("P_IDFESTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FLUJO_ESTADO_INS", p_DECRIPCIONFLUJOParameter, p_IDFESTADOParameter);
        }
    
        public virtual int FLUJO_ESTADO_UPD(string p_DECRIPCIONFLUJO, Nullable<decimal> p_IDFESTADO)
        {
            var p_DECRIPCIONFLUJOParameter = p_DECRIPCIONFLUJO != null ?
                new ObjectParameter("P_DECRIPCIONFLUJO", p_DECRIPCIONFLUJO) :
                new ObjectParameter("P_DECRIPCIONFLUJO", typeof(string));
    
            var p_IDFESTADOParameter = p_IDFESTADO.HasValue ?
                new ObjectParameter("P_IDFESTADO", p_IDFESTADO) :
                new ObjectParameter("P_IDFESTADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FLUJO_ESTADO_UPD", p_DECRIPCIONFLUJOParameter, p_IDFESTADOParameter);
        }
    
        public virtual int FLUJO_DEL(Nullable<decimal> p_IDFLUJO)
        {
            var p_IDFLUJOParameter = p_IDFLUJO.HasValue ?
                new ObjectParameter("P_IDFLUJO", p_IDFLUJO) :
                new ObjectParameter("P_IDFLUJO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FLUJO_DEL", p_IDFLUJOParameter);
        }
    
        public virtual int FLUJO_INS(string p_OBSERVACIONFLUJO, Nullable<decimal> p_FLUJO_ESTADO_IDFESTADO, Nullable<decimal> p_IDFLUJO, Nullable<System.DateTime> p_FECHACREACION, string p_NOMBREFLUJO)
        {
            var p_OBSERVACIONFLUJOParameter = p_OBSERVACIONFLUJO != null ?
                new ObjectParameter("P_OBSERVACIONFLUJO", p_OBSERVACIONFLUJO) :
                new ObjectParameter("P_OBSERVACIONFLUJO", typeof(string));
    
            var p_FLUJO_ESTADO_IDFESTADOParameter = p_FLUJO_ESTADO_IDFESTADO.HasValue ?
                new ObjectParameter("P_FLUJO_ESTADO_IDFESTADO", p_FLUJO_ESTADO_IDFESTADO) :
                new ObjectParameter("P_FLUJO_ESTADO_IDFESTADO", typeof(decimal));
    
            var p_IDFLUJOParameter = p_IDFLUJO.HasValue ?
                new ObjectParameter("P_IDFLUJO", p_IDFLUJO) :
                new ObjectParameter("P_IDFLUJO", typeof(decimal));
    
            var p_FECHACREACIONParameter = p_FECHACREACION.HasValue ?
                new ObjectParameter("P_FECHACREACION", p_FECHACREACION) :
                new ObjectParameter("P_FECHACREACION", typeof(System.DateTime));
    
            var p_NOMBREFLUJOParameter = p_NOMBREFLUJO != null ?
                new ObjectParameter("P_NOMBREFLUJO", p_NOMBREFLUJO) :
                new ObjectParameter("P_NOMBREFLUJO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FLUJO_INS", p_OBSERVACIONFLUJOParameter, p_FLUJO_ESTADO_IDFESTADOParameter, p_IDFLUJOParameter, p_FECHACREACIONParameter, p_NOMBREFLUJOParameter);
        }
    
        public virtual int FLUJO_UPD(string p_OBSERVACIONFLUJO, Nullable<decimal> p_FLUJO_ESTADO_IDFESTADO, Nullable<decimal> p_IDFLUJO, Nullable<System.DateTime> p_FECHACREACION, string p_NOMBREFLUJO)
        {
            var p_OBSERVACIONFLUJOParameter = p_OBSERVACIONFLUJO != null ?
                new ObjectParameter("P_OBSERVACIONFLUJO", p_OBSERVACIONFLUJO) :
                new ObjectParameter("P_OBSERVACIONFLUJO", typeof(string));
    
            var p_FLUJO_ESTADO_IDFESTADOParameter = p_FLUJO_ESTADO_IDFESTADO.HasValue ?
                new ObjectParameter("P_FLUJO_ESTADO_IDFESTADO", p_FLUJO_ESTADO_IDFESTADO) :
                new ObjectParameter("P_FLUJO_ESTADO_IDFESTADO", typeof(decimal));
    
            var p_IDFLUJOParameter = p_IDFLUJO.HasValue ?
                new ObjectParameter("P_IDFLUJO", p_IDFLUJO) :
                new ObjectParameter("P_IDFLUJO", typeof(decimal));
    
            var p_FECHACREACIONParameter = p_FECHACREACION.HasValue ?
                new ObjectParameter("P_FECHACREACION", p_FECHACREACION) :
                new ObjectParameter("P_FECHACREACION", typeof(System.DateTime));
    
            var p_NOMBREFLUJOParameter = p_NOMBREFLUJO != null ?
                new ObjectParameter("P_NOMBREFLUJO", p_NOMBREFLUJO) :
                new ObjectParameter("P_NOMBREFLUJO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FLUJO_UPD", p_OBSERVACIONFLUJOParameter, p_FLUJO_ESTADO_IDFESTADOParameter, p_IDFLUJOParameter, p_FECHACREACIONParameter, p_NOMBREFLUJOParameter);
        }
    
        public virtual int FLUJO_TAREA_DEL(Nullable<decimal> p_IDFTAREA)
        {
            var p_IDFTAREAParameter = p_IDFTAREA.HasValue ?
                new ObjectParameter("P_IDFTAREA", p_IDFTAREA) :
                new ObjectParameter("P_IDFTAREA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FLUJO_TAREA_DEL", p_IDFTAREAParameter);
        }
    
        public virtual int FLUJO_TAREA_INS(Nullable<System.DateTime> p_FECHA, Nullable<decimal> p_IDFTAREA, Nullable<decimal> p_FLUJO_IDFLUJO, Nullable<decimal> p_TAREA_IDTAREA)
        {
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_IDFTAREAParameter = p_IDFTAREA.HasValue ?
                new ObjectParameter("P_IDFTAREA", p_IDFTAREA) :
                new ObjectParameter("P_IDFTAREA", typeof(decimal));
    
            var p_FLUJO_IDFLUJOParameter = p_FLUJO_IDFLUJO.HasValue ?
                new ObjectParameter("P_FLUJO_IDFLUJO", p_FLUJO_IDFLUJO) :
                new ObjectParameter("P_FLUJO_IDFLUJO", typeof(decimal));
    
            var p_TAREA_IDTAREAParameter = p_TAREA_IDTAREA.HasValue ?
                new ObjectParameter("P_TAREA_IDTAREA", p_TAREA_IDTAREA) :
                new ObjectParameter("P_TAREA_IDTAREA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FLUJO_TAREA_INS", p_FECHAParameter, p_IDFTAREAParameter, p_FLUJO_IDFLUJOParameter, p_TAREA_IDTAREAParameter);
        }
    
        public virtual int FLUJO_TAREA_UPD(Nullable<System.DateTime> p_FECHA, Nullable<decimal> p_IDFTAREA, Nullable<decimal> p_FLUJO_IDFLUJO, Nullable<decimal> p_TAREA_IDTAREA)
        {
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_IDFTAREAParameter = p_IDFTAREA.HasValue ?
                new ObjectParameter("P_IDFTAREA", p_IDFTAREA) :
                new ObjectParameter("P_IDFTAREA", typeof(decimal));
    
            var p_FLUJO_IDFLUJOParameter = p_FLUJO_IDFLUJO.HasValue ?
                new ObjectParameter("P_FLUJO_IDFLUJO", p_FLUJO_IDFLUJO) :
                new ObjectParameter("P_FLUJO_IDFLUJO", typeof(decimal));
    
            var p_TAREA_IDTAREAParameter = p_TAREA_IDTAREA.HasValue ?
                new ObjectParameter("P_TAREA_IDTAREA", p_TAREA_IDTAREA) :
                new ObjectParameter("P_TAREA_IDTAREA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FLUJO_TAREA_UPD", p_FECHAParameter, p_IDFTAREAParameter, p_FLUJO_IDFLUJOParameter, p_TAREA_IDTAREAParameter);
        }
    
        public virtual int FUNCIONARIO_DEL(Nullable<decimal> p_IDFUNCIONARIO)
        {
            var p_IDFUNCIONARIOParameter = p_IDFUNCIONARIO.HasValue ?
                new ObjectParameter("P_IDFUNCIONARIO", p_IDFUNCIONARIO) :
                new ObjectParameter("P_IDFUNCIONARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FUNCIONARIO_DEL", p_IDFUNCIONARIOParameter);
        }
    
        public virtual int FUNCIONARIO_INS(Nullable<decimal> p_IDFUNCIONARIO, Nullable<decimal> p_RUT, string p_PNOMBRE, string p_SNOMBRE, string p_DIRECCION, string p_DV, string p_CORREO, Nullable<decimal> p_UNIDAD_IDUNIDAD, string p_APATERNO, string p_AMATERNO, Nullable<decimal> p_TELEFONO)
        {
            var p_IDFUNCIONARIOParameter = p_IDFUNCIONARIO.HasValue ?
                new ObjectParameter("P_IDFUNCIONARIO", p_IDFUNCIONARIO) :
                new ObjectParameter("P_IDFUNCIONARIO", typeof(decimal));
    
            var p_RUTParameter = p_RUT.HasValue ?
                new ObjectParameter("P_RUT", p_RUT) :
                new ObjectParameter("P_RUT", typeof(decimal));
    
            var p_PNOMBREParameter = p_PNOMBRE != null ?
                new ObjectParameter("P_PNOMBRE", p_PNOMBRE) :
                new ObjectParameter("P_PNOMBRE", typeof(string));
    
            var p_SNOMBREParameter = p_SNOMBRE != null ?
                new ObjectParameter("P_SNOMBRE", p_SNOMBRE) :
                new ObjectParameter("P_SNOMBRE", typeof(string));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_DVParameter = p_DV != null ?
                new ObjectParameter("P_DV", p_DV) :
                new ObjectParameter("P_DV", typeof(string));
    
            var p_CORREOParameter = p_CORREO != null ?
                new ObjectParameter("P_CORREO", p_CORREO) :
                new ObjectParameter("P_CORREO", typeof(string));
    
            var p_UNIDAD_IDUNIDADParameter = p_UNIDAD_IDUNIDAD.HasValue ?
                new ObjectParameter("P_UNIDAD_IDUNIDAD", p_UNIDAD_IDUNIDAD) :
                new ObjectParameter("P_UNIDAD_IDUNIDAD", typeof(decimal));
    
            var p_APATERNOParameter = p_APATERNO != null ?
                new ObjectParameter("P_APATERNO", p_APATERNO) :
                new ObjectParameter("P_APATERNO", typeof(string));
    
            var p_AMATERNOParameter = p_AMATERNO != null ?
                new ObjectParameter("P_AMATERNO", p_AMATERNO) :
                new ObjectParameter("P_AMATERNO", typeof(string));
    
            var p_TELEFONOParameter = p_TELEFONO.HasValue ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FUNCIONARIO_INS", p_IDFUNCIONARIOParameter, p_RUTParameter, p_PNOMBREParameter, p_SNOMBREParameter, p_DIRECCIONParameter, p_DVParameter, p_CORREOParameter, p_UNIDAD_IDUNIDADParameter, p_APATERNOParameter, p_AMATERNOParameter, p_TELEFONOParameter);
        }
    
        public virtual int FUNCIONARIO_UPD(Nullable<decimal> p_IDFUNCIONARIO, Nullable<decimal> p_RUT, string p_PNOMBRE, string p_SNOMBRE, string p_DIRECCION, string p_DV, string p_CORREO, Nullable<decimal> p_UNIDAD_IDUNIDAD, string p_APATERNO, string p_AMATERNO, Nullable<decimal> p_TELEFONO)
        {
            var p_IDFUNCIONARIOParameter = p_IDFUNCIONARIO.HasValue ?
                new ObjectParameter("P_IDFUNCIONARIO", p_IDFUNCIONARIO) :
                new ObjectParameter("P_IDFUNCIONARIO", typeof(decimal));
    
            var p_RUTParameter = p_RUT.HasValue ?
                new ObjectParameter("P_RUT", p_RUT) :
                new ObjectParameter("P_RUT", typeof(decimal));
    
            var p_PNOMBREParameter = p_PNOMBRE != null ?
                new ObjectParameter("P_PNOMBRE", p_PNOMBRE) :
                new ObjectParameter("P_PNOMBRE", typeof(string));
    
            var p_SNOMBREParameter = p_SNOMBRE != null ?
                new ObjectParameter("P_SNOMBRE", p_SNOMBRE) :
                new ObjectParameter("P_SNOMBRE", typeof(string));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_DVParameter = p_DV != null ?
                new ObjectParameter("P_DV", p_DV) :
                new ObjectParameter("P_DV", typeof(string));
    
            var p_CORREOParameter = p_CORREO != null ?
                new ObjectParameter("P_CORREO", p_CORREO) :
                new ObjectParameter("P_CORREO", typeof(string));
    
            var p_UNIDAD_IDUNIDADParameter = p_UNIDAD_IDUNIDAD.HasValue ?
                new ObjectParameter("P_UNIDAD_IDUNIDAD", p_UNIDAD_IDUNIDAD) :
                new ObjectParameter("P_UNIDAD_IDUNIDAD", typeof(decimal));
    
            var p_APATERNOParameter = p_APATERNO != null ?
                new ObjectParameter("P_APATERNO", p_APATERNO) :
                new ObjectParameter("P_APATERNO", typeof(string));
    
            var p_AMATERNOParameter = p_AMATERNO != null ?
                new ObjectParameter("P_AMATERNO", p_AMATERNO) :
                new ObjectParameter("P_AMATERNO", typeof(string));
    
            var p_TELEFONOParameter = p_TELEFONO.HasValue ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FUNCIONARIO_UPD", p_IDFUNCIONARIOParameter, p_RUTParameter, p_PNOMBREParameter, p_SNOMBREParameter, p_DIRECCIONParameter, p_DVParameter, p_CORREOParameter, p_UNIDAD_IDUNIDADParameter, p_APATERNOParameter, p_AMATERNOParameter, p_TELEFONOParameter);
        }
    
        public virtual int FUNCIONARIO_TAREA_DEL(Nullable<decimal> p_IDFUTAREA)
        {
            var p_IDFUTAREAParameter = p_IDFUTAREA.HasValue ?
                new ObjectParameter("P_IDFUTAREA", p_IDFUTAREA) :
                new ObjectParameter("P_IDFUTAREA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FUNCIONARIO_TAREA_DEL", p_IDFUTAREAParameter);
        }
    
        public virtual int FUNCIONARIO_TAREA_INS(Nullable<System.DateTime> p_FECHAPLAZO, Nullable<decimal> p_FUNCIONARIO_IDFUNCIONARIO, Nullable<decimal> p_IDFUTAREA, Nullable<decimal> p_TAREA_IDTAREA)
        {
            var p_FECHAPLAZOParameter = p_FECHAPLAZO.HasValue ?
                new ObjectParameter("P_FECHAPLAZO", p_FECHAPLAZO) :
                new ObjectParameter("P_FECHAPLAZO", typeof(System.DateTime));
    
            var p_FUNCIONARIO_IDFUNCIONARIOParameter = p_FUNCIONARIO_IDFUNCIONARIO.HasValue ?
                new ObjectParameter("P_FUNCIONARIO_IDFUNCIONARIO", p_FUNCIONARIO_IDFUNCIONARIO) :
                new ObjectParameter("P_FUNCIONARIO_IDFUNCIONARIO", typeof(decimal));
    
            var p_IDFUTAREAParameter = p_IDFUTAREA.HasValue ?
                new ObjectParameter("P_IDFUTAREA", p_IDFUTAREA) :
                new ObjectParameter("P_IDFUTAREA", typeof(decimal));
    
            var p_TAREA_IDTAREAParameter = p_TAREA_IDTAREA.HasValue ?
                new ObjectParameter("P_TAREA_IDTAREA", p_TAREA_IDTAREA) :
                new ObjectParameter("P_TAREA_IDTAREA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FUNCIONARIO_TAREA_INS", p_FECHAPLAZOParameter, p_FUNCIONARIO_IDFUNCIONARIOParameter, p_IDFUTAREAParameter, p_TAREA_IDTAREAParameter);
        }
    
        public virtual int FUNCIONARIO_TAREA_UPD(Nullable<System.DateTime> p_FECHAPLAZO, Nullable<decimal> p_FUNCIONARIO_IDFUNCIONARIO, Nullable<decimal> p_IDFUTAREA, Nullable<decimal> p_TAREA_IDTAREA)
        {
            var p_FECHAPLAZOParameter = p_FECHAPLAZO.HasValue ?
                new ObjectParameter("P_FECHAPLAZO", p_FECHAPLAZO) :
                new ObjectParameter("P_FECHAPLAZO", typeof(System.DateTime));
    
            var p_FUNCIONARIO_IDFUNCIONARIOParameter = p_FUNCIONARIO_IDFUNCIONARIO.HasValue ?
                new ObjectParameter("P_FUNCIONARIO_IDFUNCIONARIO", p_FUNCIONARIO_IDFUNCIONARIO) :
                new ObjectParameter("P_FUNCIONARIO_IDFUNCIONARIO", typeof(decimal));
    
            var p_IDFUTAREAParameter = p_IDFUTAREA.HasValue ?
                new ObjectParameter("P_IDFUTAREA", p_IDFUTAREA) :
                new ObjectParameter("P_IDFUTAREA", typeof(decimal));
    
            var p_TAREA_IDTAREAParameter = p_TAREA_IDTAREA.HasValue ?
                new ObjectParameter("P_TAREA_IDTAREA", p_TAREA_IDTAREA) :
                new ObjectParameter("P_TAREA_IDTAREA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FUNCIONARIO_TAREA_UPD", p_FECHAPLAZOParameter, p_FUNCIONARIO_IDFUNCIONARIOParameter, p_IDFUTAREAParameter, p_TAREA_IDTAREAParameter);
        }
    
        public virtual int PROBLEMA_EJECUCION_DEL(Nullable<decimal> p_IDPEJECUCION)
        {
            var p_IDPEJECUCIONParameter = p_IDPEJECUCION.HasValue ?
                new ObjectParameter("P_IDPEJECUCION", p_IDPEJECUCION) :
                new ObjectParameter("P_IDPEJECUCION", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROBLEMA_EJECUCION_DEL", p_IDPEJECUCIONParameter);
        }
    
        public virtual int PROBLEMA_EJECUCION_INS(Nullable<decimal> p_IDPEJECUCION, Nullable<decimal> p_EJECUCION_TAREA_IDEJTAREA, Nullable<System.DateTime> p_FECHA, string p_DESCRIPCIONPROBLEMA)
        {
            var p_IDPEJECUCIONParameter = p_IDPEJECUCION.HasValue ?
                new ObjectParameter("P_IDPEJECUCION", p_IDPEJECUCION) :
                new ObjectParameter("P_IDPEJECUCION", typeof(decimal));
    
            var p_EJECUCION_TAREA_IDEJTAREAParameter = p_EJECUCION_TAREA_IDEJTAREA.HasValue ?
                new ObjectParameter("P_EJECUCION_TAREA_IDEJTAREA", p_EJECUCION_TAREA_IDEJTAREA) :
                new ObjectParameter("P_EJECUCION_TAREA_IDEJTAREA", typeof(decimal));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_DESCRIPCIONPROBLEMAParameter = p_DESCRIPCIONPROBLEMA != null ?
                new ObjectParameter("P_DESCRIPCIONPROBLEMA", p_DESCRIPCIONPROBLEMA) :
                new ObjectParameter("P_DESCRIPCIONPROBLEMA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROBLEMA_EJECUCION_INS", p_IDPEJECUCIONParameter, p_EJECUCION_TAREA_IDEJTAREAParameter, p_FECHAParameter, p_DESCRIPCIONPROBLEMAParameter);
        }
    
        public virtual int PROBLEMA_EJECUCION_UPD(Nullable<decimal> p_IDPEJECUCION, Nullable<decimal> p_EJECUCION_TAREA_IDEJTAREA, Nullable<System.DateTime> p_FECHA, string p_DESCRIPCIONPROBLEMA)
        {
            var p_IDPEJECUCIONParameter = p_IDPEJECUCION.HasValue ?
                new ObjectParameter("P_IDPEJECUCION", p_IDPEJECUCION) :
                new ObjectParameter("P_IDPEJECUCION", typeof(decimal));
    
            var p_EJECUCION_TAREA_IDEJTAREAParameter = p_EJECUCION_TAREA_IDEJTAREA.HasValue ?
                new ObjectParameter("P_EJECUCION_TAREA_IDEJTAREA", p_EJECUCION_TAREA_IDEJTAREA) :
                new ObjectParameter("P_EJECUCION_TAREA_IDEJTAREA", typeof(decimal));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_DESCRIPCIONPROBLEMAParameter = p_DESCRIPCIONPROBLEMA != null ?
                new ObjectParameter("P_DESCRIPCIONPROBLEMA", p_DESCRIPCIONPROBLEMA) :
                new ObjectParameter("P_DESCRIPCIONPROBLEMA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROBLEMA_EJECUCION_UPD", p_IDPEJECUCIONParameter, p_EJECUCION_TAREA_IDEJTAREAParameter, p_FECHAParameter, p_DESCRIPCIONPROBLEMAParameter);
        }
    
        public virtual int RESOLUCION_PROBLEMA_DEL(Nullable<decimal> p_IDRPROBLEMA)
        {
            var p_IDRPROBLEMAParameter = p_IDRPROBLEMA.HasValue ?
                new ObjectParameter("P_IDRPROBLEMA", p_IDRPROBLEMA) :
                new ObjectParameter("P_IDRPROBLEMA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RESOLUCION_PROBLEMA_DEL", p_IDRPROBLEMAParameter);
        }
    
        public virtual int RESOLUCION_PROBLEMA_INS(string p_DETALLE, Nullable<System.DateTime> p_FECHAINICIO, Nullable<decimal> p_PR_EJECUCION_IDPEJECUCION, string p_OBSERVACIONES, Nullable<decimal> p_ESTADO_SOLUCION_IDESOLUCION, Nullable<System.DateTime> p_FECHATERMINO, Nullable<decimal> p_IDRPROBLEMA)
        {
            var p_DETALLEParameter = p_DETALLE != null ?
                new ObjectParameter("P_DETALLE", p_DETALLE) :
                new ObjectParameter("P_DETALLE", typeof(string));
    
            var p_FECHAINICIOParameter = p_FECHAINICIO.HasValue ?
                new ObjectParameter("P_FECHAINICIO", p_FECHAINICIO) :
                new ObjectParameter("P_FECHAINICIO", typeof(System.DateTime));
    
            var p_PR_EJECUCION_IDPEJECUCIONParameter = p_PR_EJECUCION_IDPEJECUCION.HasValue ?
                new ObjectParameter("P_PR_EJECUCION_IDPEJECUCION", p_PR_EJECUCION_IDPEJECUCION) :
                new ObjectParameter("P_PR_EJECUCION_IDPEJECUCION", typeof(decimal));
    
            var p_OBSERVACIONESParameter = p_OBSERVACIONES != null ?
                new ObjectParameter("P_OBSERVACIONES", p_OBSERVACIONES) :
                new ObjectParameter("P_OBSERVACIONES", typeof(string));
    
            var p_ESTADO_SOLUCION_IDESOLUCIONParameter = p_ESTADO_SOLUCION_IDESOLUCION.HasValue ?
                new ObjectParameter("P_ESTADO_SOLUCION_IDESOLUCION", p_ESTADO_SOLUCION_IDESOLUCION) :
                new ObjectParameter("P_ESTADO_SOLUCION_IDESOLUCION", typeof(decimal));
    
            var p_FECHATERMINOParameter = p_FECHATERMINO.HasValue ?
                new ObjectParameter("P_FECHATERMINO", p_FECHATERMINO) :
                new ObjectParameter("P_FECHATERMINO", typeof(System.DateTime));
    
            var p_IDRPROBLEMAParameter = p_IDRPROBLEMA.HasValue ?
                new ObjectParameter("P_IDRPROBLEMA", p_IDRPROBLEMA) :
                new ObjectParameter("P_IDRPROBLEMA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RESOLUCION_PROBLEMA_INS", p_DETALLEParameter, p_FECHAINICIOParameter, p_PR_EJECUCION_IDPEJECUCIONParameter, p_OBSERVACIONESParameter, p_ESTADO_SOLUCION_IDESOLUCIONParameter, p_FECHATERMINOParameter, p_IDRPROBLEMAParameter);
        }
    
        public virtual int RESOLUCION_PROBLEMA_UPD(string p_DETALLE, Nullable<System.DateTime> p_FECHAINICIO, Nullable<decimal> p_PR_EJECUCION_IDPEJECUCION, string p_OBSERVACIONES, Nullable<decimal> p_ESTADO_SOLUCION_IDESOLUCION, Nullable<System.DateTime> p_FECHATERMINO, Nullable<decimal> p_IDRPROBLEMA)
        {
            var p_DETALLEParameter = p_DETALLE != null ?
                new ObjectParameter("P_DETALLE", p_DETALLE) :
                new ObjectParameter("P_DETALLE", typeof(string));
    
            var p_FECHAINICIOParameter = p_FECHAINICIO.HasValue ?
                new ObjectParameter("P_FECHAINICIO", p_FECHAINICIO) :
                new ObjectParameter("P_FECHAINICIO", typeof(System.DateTime));
    
            var p_PR_EJECUCION_IDPEJECUCIONParameter = p_PR_EJECUCION_IDPEJECUCION.HasValue ?
                new ObjectParameter("P_PR_EJECUCION_IDPEJECUCION", p_PR_EJECUCION_IDPEJECUCION) :
                new ObjectParameter("P_PR_EJECUCION_IDPEJECUCION", typeof(decimal));
    
            var p_OBSERVACIONESParameter = p_OBSERVACIONES != null ?
                new ObjectParameter("P_OBSERVACIONES", p_OBSERVACIONES) :
                new ObjectParameter("P_OBSERVACIONES", typeof(string));
    
            var p_ESTADO_SOLUCION_IDESOLUCIONParameter = p_ESTADO_SOLUCION_IDESOLUCION.HasValue ?
                new ObjectParameter("P_ESTADO_SOLUCION_IDESOLUCION", p_ESTADO_SOLUCION_IDESOLUCION) :
                new ObjectParameter("P_ESTADO_SOLUCION_IDESOLUCION", typeof(decimal));
    
            var p_FECHATERMINOParameter = p_FECHATERMINO.HasValue ?
                new ObjectParameter("P_FECHATERMINO", p_FECHATERMINO) :
                new ObjectParameter("P_FECHATERMINO", typeof(System.DateTime));
    
            var p_IDRPROBLEMAParameter = p_IDRPROBLEMA.HasValue ?
                new ObjectParameter("P_IDRPROBLEMA", p_IDRPROBLEMA) :
                new ObjectParameter("P_IDRPROBLEMA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RESOLUCION_PROBLEMA_UPD", p_DETALLEParameter, p_FECHAINICIOParameter, p_PR_EJECUCION_IDPEJECUCIONParameter, p_OBSERVACIONESParameter, p_ESTADO_SOLUCION_IDESOLUCIONParameter, p_FECHATERMINOParameter, p_IDRPROBLEMAParameter);
        }
    
        public virtual int ROL_DEL(Nullable<decimal> p_IDROL)
        {
            var p_IDROLParameter = p_IDROL.HasValue ?
                new ObjectParameter("P_IDROL", p_IDROL) :
                new ObjectParameter("P_IDROL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ROL_DEL", p_IDROLParameter);
        }
    
        public virtual int ROL_INS(Nullable<decimal> p_IDROL, string p_DESCRIPCION, Nullable<decimal> p_US_FUNCIONARIO_IDUFUNCIONARIO)
        {
            var p_IDROLParameter = p_IDROL.HasValue ?
                new ObjectParameter("P_IDROL", p_IDROL) :
                new ObjectParameter("P_IDROL", typeof(decimal));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_US_FUNCIONARIO_IDUFUNCIONARIOParameter = p_US_FUNCIONARIO_IDUFUNCIONARIO.HasValue ?
                new ObjectParameter("P_US_FUNCIONARIO_IDUFUNCIONARIO", p_US_FUNCIONARIO_IDUFUNCIONARIO) :
                new ObjectParameter("P_US_FUNCIONARIO_IDUFUNCIONARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ROL_INS", p_IDROLParameter, p_DESCRIPCIONParameter, p_US_FUNCIONARIO_IDUFUNCIONARIOParameter);
        }
    
        public virtual int ROL_UPD(Nullable<decimal> p_IDROL, string p_DESCRIPCION, Nullable<decimal> p_US_FUNCIONARIO_IDUFUNCIONARIO)
        {
            var p_IDROLParameter = p_IDROL.HasValue ?
                new ObjectParameter("P_IDROL", p_IDROL) :
                new ObjectParameter("P_IDROL", typeof(decimal));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_US_FUNCIONARIO_IDUFUNCIONARIOParameter = p_US_FUNCIONARIO_IDUFUNCIONARIO.HasValue ?
                new ObjectParameter("P_US_FUNCIONARIO_IDUFUNCIONARIO", p_US_FUNCIONARIO_IDUFUNCIONARIO) :
                new ObjectParameter("P_US_FUNCIONARIO_IDUFUNCIONARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ROL_UPD", p_IDROLParameter, p_DESCRIPCIONParameter, p_US_FUNCIONARIO_IDUFUNCIONARIOParameter);
        }
    
        public virtual int TAREA_DEL(Nullable<decimal> p_IDTAREA)
        {
            var p_IDTAREAParameter = p_IDTAREA.HasValue ?
                new ObjectParameter("P_IDTAREA", p_IDTAREA) :
                new ObjectParameter("P_IDTAREA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TAREA_DEL", p_IDTAREAParameter);
        }
    
        public virtual int TAREA_INS(Nullable<decimal> p_IDTAREA, Nullable<System.DateTime> p_FECHACREACION, Nullable<decimal> p_ESTADO_TAREA_IDTAREA, string p_NOMBRETAREA)
        {
            var p_IDTAREAParameter = p_IDTAREA.HasValue ?
                new ObjectParameter("P_IDTAREA", p_IDTAREA) :
                new ObjectParameter("P_IDTAREA", typeof(decimal));
    
            var p_FECHACREACIONParameter = p_FECHACREACION.HasValue ?
                new ObjectParameter("P_FECHACREACION", p_FECHACREACION) :
                new ObjectParameter("P_FECHACREACION", typeof(System.DateTime));
    
            var p_ESTADO_TAREA_IDTAREAParameter = p_ESTADO_TAREA_IDTAREA.HasValue ?
                new ObjectParameter("P_ESTADO_TAREA_IDTAREA", p_ESTADO_TAREA_IDTAREA) :
                new ObjectParameter("P_ESTADO_TAREA_IDTAREA", typeof(decimal));
    
            var p_NOMBRETAREAParameter = p_NOMBRETAREA != null ?
                new ObjectParameter("P_NOMBRETAREA", p_NOMBRETAREA) :
                new ObjectParameter("P_NOMBRETAREA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TAREA_INS", p_IDTAREAParameter, p_FECHACREACIONParameter, p_ESTADO_TAREA_IDTAREAParameter, p_NOMBRETAREAParameter);
        }
    
        public virtual int TAREA_UPD(Nullable<decimal> p_IDTAREA, Nullable<System.DateTime> p_FECHACREACION, Nullable<decimal> p_ESTADO_TAREA_IDTAREA, string p_NOMBRETAREA)
        {
            var p_IDTAREAParameter = p_IDTAREA.HasValue ?
                new ObjectParameter("P_IDTAREA", p_IDTAREA) :
                new ObjectParameter("P_IDTAREA", typeof(decimal));
    
            var p_FECHACREACIONParameter = p_FECHACREACION.HasValue ?
                new ObjectParameter("P_FECHACREACION", p_FECHACREACION) :
                new ObjectParameter("P_FECHACREACION", typeof(System.DateTime));
    
            var p_ESTADO_TAREA_IDTAREAParameter = p_ESTADO_TAREA_IDTAREA.HasValue ?
                new ObjectParameter("P_ESTADO_TAREA_IDTAREA", p_ESTADO_TAREA_IDTAREA) :
                new ObjectParameter("P_ESTADO_TAREA_IDTAREA", typeof(decimal));
    
            var p_NOMBRETAREAParameter = p_NOMBRETAREA != null ?
                new ObjectParameter("P_NOMBRETAREA", p_NOMBRETAREA) :
                new ObjectParameter("P_NOMBRETAREA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TAREA_UPD", p_IDTAREAParameter, p_FECHACREACIONParameter, p_ESTADO_TAREA_IDTAREAParameter, p_NOMBRETAREAParameter);
        }
    
        public virtual int UNIDAD_DEL(Nullable<decimal> p_IDUNIDAD)
        {
            var p_IDUNIDADParameter = p_IDUNIDAD.HasValue ?
                new ObjectParameter("P_IDUNIDAD", p_IDUNIDAD) :
                new ObjectParameter("P_IDUNIDAD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UNIDAD_DEL", p_IDUNIDADParameter);
        }
    
        public virtual int UNIDAD_INS(Nullable<decimal> p_IDUNIDAD, string p_NOMBREUNIDAD, Nullable<decimal> p_EMPRESA_RUTEMPRESA, Nullable<decimal> p_EMPRESA_IDEMPRESA)
        {
            var p_IDUNIDADParameter = p_IDUNIDAD.HasValue ?
                new ObjectParameter("P_IDUNIDAD", p_IDUNIDAD) :
                new ObjectParameter("P_IDUNIDAD", typeof(decimal));
    
            var p_NOMBREUNIDADParameter = p_NOMBREUNIDAD != null ?
                new ObjectParameter("P_NOMBREUNIDAD", p_NOMBREUNIDAD) :
                new ObjectParameter("P_NOMBREUNIDAD", typeof(string));
    
            var p_EMPRESA_RUTEMPRESAParameter = p_EMPRESA_RUTEMPRESA.HasValue ?
                new ObjectParameter("P_EMPRESA_RUTEMPRESA", p_EMPRESA_RUTEMPRESA) :
                new ObjectParameter("P_EMPRESA_RUTEMPRESA", typeof(decimal));
    
            var p_EMPRESA_IDEMPRESAParameter = p_EMPRESA_IDEMPRESA.HasValue ?
                new ObjectParameter("P_EMPRESA_IDEMPRESA", p_EMPRESA_IDEMPRESA) :
                new ObjectParameter("P_EMPRESA_IDEMPRESA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UNIDAD_INS", p_IDUNIDADParameter, p_NOMBREUNIDADParameter, p_EMPRESA_RUTEMPRESAParameter, p_EMPRESA_IDEMPRESAParameter);
        }
    
        public virtual int UNIDAD_UPD(Nullable<decimal> p_IDUNIDAD, string p_NOMBREUNIDAD, Nullable<decimal> p_EMPRESA_RUTEMPRESA, Nullable<decimal> p_EMPRESA_IDEMPRESA)
        {
            var p_IDUNIDADParameter = p_IDUNIDAD.HasValue ?
                new ObjectParameter("P_IDUNIDAD", p_IDUNIDAD) :
                new ObjectParameter("P_IDUNIDAD", typeof(decimal));
    
            var p_NOMBREUNIDADParameter = p_NOMBREUNIDAD != null ?
                new ObjectParameter("P_NOMBREUNIDAD", p_NOMBREUNIDAD) :
                new ObjectParameter("P_NOMBREUNIDAD", typeof(string));
    
            var p_EMPRESA_RUTEMPRESAParameter = p_EMPRESA_RUTEMPRESA.HasValue ?
                new ObjectParameter("P_EMPRESA_RUTEMPRESA", p_EMPRESA_RUTEMPRESA) :
                new ObjectParameter("P_EMPRESA_RUTEMPRESA", typeof(decimal));
    
            var p_EMPRESA_IDEMPRESAParameter = p_EMPRESA_IDEMPRESA.HasValue ?
                new ObjectParameter("P_EMPRESA_IDEMPRESA", p_EMPRESA_IDEMPRESA) :
                new ObjectParameter("P_EMPRESA_IDEMPRESA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UNIDAD_UPD", p_IDUNIDADParameter, p_NOMBREUNIDADParameter, p_EMPRESA_RUTEMPRESAParameter, p_EMPRESA_IDEMPRESAParameter);
        }
    
        public virtual int USUARIO_FUNCIONARIO_DEL(Nullable<decimal> p_IDUFUNCIONARIO)
        {
            var p_IDUFUNCIONARIOParameter = p_IDUFUNCIONARIO.HasValue ?
                new ObjectParameter("P_IDUFUNCIONARIO", p_IDUFUNCIONARIO) :
                new ObjectParameter("P_IDUFUNCIONARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USUARIO_FUNCIONARIO_DEL", p_IDUFUNCIONARIOParameter);
        }
    
        public virtual int USUARIO_FUNCIONARIO_INS(Nullable<decimal> p_FUNCIONARIO_IDFUNCIONARIO, Nullable<decimal> p_IDUFUNCIONARIO, Nullable<decimal> p_USUARIO_USUARIO_ID)
        {
            var p_FUNCIONARIO_IDFUNCIONARIOParameter = p_FUNCIONARIO_IDFUNCIONARIO.HasValue ?
                new ObjectParameter("P_FUNCIONARIO_IDFUNCIONARIO", p_FUNCIONARIO_IDFUNCIONARIO) :
                new ObjectParameter("P_FUNCIONARIO_IDFUNCIONARIO", typeof(decimal));
    
            var p_IDUFUNCIONARIOParameter = p_IDUFUNCIONARIO.HasValue ?
                new ObjectParameter("P_IDUFUNCIONARIO", p_IDUFUNCIONARIO) :
                new ObjectParameter("P_IDUFUNCIONARIO", typeof(decimal));
    
            var p_USUARIO_USUARIO_IDParameter = p_USUARIO_USUARIO_ID.HasValue ?
                new ObjectParameter("P_USUARIO_USUARIO_ID", p_USUARIO_USUARIO_ID) :
                new ObjectParameter("P_USUARIO_USUARIO_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USUARIO_FUNCIONARIO_INS", p_FUNCIONARIO_IDFUNCIONARIOParameter, p_IDUFUNCIONARIOParameter, p_USUARIO_USUARIO_IDParameter);
        }
    
        public virtual int USUARIO_FUNCIONARIO_UPD(Nullable<decimal> p_FUNCIONARIO_IDFUNCIONARIO, Nullable<decimal> p_IDUFUNCIONARIO, Nullable<decimal> p_USUARIO_USUARIO_ID)
        {
            var p_FUNCIONARIO_IDFUNCIONARIOParameter = p_FUNCIONARIO_IDFUNCIONARIO.HasValue ?
                new ObjectParameter("P_FUNCIONARIO_IDFUNCIONARIO", p_FUNCIONARIO_IDFUNCIONARIO) :
                new ObjectParameter("P_FUNCIONARIO_IDFUNCIONARIO", typeof(decimal));
    
            var p_IDUFUNCIONARIOParameter = p_IDUFUNCIONARIO.HasValue ?
                new ObjectParameter("P_IDUFUNCIONARIO", p_IDUFUNCIONARIO) :
                new ObjectParameter("P_IDUFUNCIONARIO", typeof(decimal));
    
            var p_USUARIO_USUARIO_IDParameter = p_USUARIO_USUARIO_ID.HasValue ?
                new ObjectParameter("P_USUARIO_USUARIO_ID", p_USUARIO_USUARIO_ID) :
                new ObjectParameter("P_USUARIO_USUARIO_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USUARIO_FUNCIONARIO_UPD", p_FUNCIONARIO_IDFUNCIONARIOParameter, p_IDUFUNCIONARIOParameter, p_USUARIO_USUARIO_IDParameter);
        }
    
        public virtual int USUARIO_DEL(Nullable<decimal> p_USUARIO_ID)
        {
            var p_USUARIO_IDParameter = p_USUARIO_ID.HasValue ?
                new ObjectParameter("P_USUARIO_ID", p_USUARIO_ID) :
                new ObjectParameter("P_USUARIO_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USUARIO_DEL", p_USUARIO_IDParameter);
        }
    
        public virtual int USUARIO_INS(string p_NOMBREUSUARIO, string p_CONTRASEÑA, Nullable<decimal> p_USUARIO_ID)
        {
            var p_NOMBREUSUARIOParameter = p_NOMBREUSUARIO != null ?
                new ObjectParameter("P_NOMBREUSUARIO", p_NOMBREUSUARIO) :
                new ObjectParameter("P_NOMBREUSUARIO", typeof(string));
    
            var p_CONTRASEÑAParameter = p_CONTRASEÑA != null ?
                new ObjectParameter("P_CONTRASEÑA", p_CONTRASEÑA) :
                new ObjectParameter("P_CONTRASEÑA", typeof(string));
    
            var p_USUARIO_IDParameter = p_USUARIO_ID.HasValue ?
                new ObjectParameter("P_USUARIO_ID", p_USUARIO_ID) :
                new ObjectParameter("P_USUARIO_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USUARIO_INS", p_NOMBREUSUARIOParameter, p_CONTRASEÑAParameter, p_USUARIO_IDParameter);
        }
    
        public virtual int USUARIO_UPD(string p_NOMBREUSUARIO, string p_CONTRASEÑA, Nullable<decimal> p_USUARIO_ID)
        {
            var p_NOMBREUSUARIOParameter = p_NOMBREUSUARIO != null ?
                new ObjectParameter("P_NOMBREUSUARIO", p_NOMBREUSUARIO) :
                new ObjectParameter("P_NOMBREUSUARIO", typeof(string));
    
            var p_CONTRASEÑAParameter = p_CONTRASEÑA != null ?
                new ObjectParameter("P_CONTRASEÑA", p_CONTRASEÑA) :
                new ObjectParameter("P_CONTRASEÑA", typeof(string));
    
            var p_USUARIO_IDParameter = p_USUARIO_ID.HasValue ?
                new ObjectParameter("P_USUARIO_ID", p_USUARIO_ID) :
                new ObjectParameter("P_USUARIO_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USUARIO_UPD", p_NOMBREUSUARIOParameter, p_CONTRASEÑAParameter, p_USUARIO_IDParameter);
        }
    }
}
