//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROBLEMA_EJECUCION
    {
        public PROBLEMA_EJECUCION()
        {
            this.RESOLUCION_PROBLEMA = new HashSet<RESOLUCION_PROBLEMA>();
        }
    
        public int IDPEJECUCION { get; set; }
        public string DESCRIPCIONPROBLEMA { get; set; }
        public System.DateTime FECHA { get; set; }
        public short EJECUCION_TAREA_IDEJTAREA { get; set; }
    
        public virtual EJECUCION_TAREA EJECUCION_TAREA { get; set; }
        public virtual ICollection<RESOLUCION_PROBLEMA> RESOLUCION_PROBLEMA { get; set; }
    }
}
