//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOLUCION_PROBLEMA
    {
        public short IDRPROBLEMA { get; set; }
        public string OBSERVACIONES { get; set; }
        public string DETALLE { get; set; }
        public System.DateTime FECHAINICIO { get; set; }
        public System.DateTime FECHATERMINO { get; set; }
        public int PR_EJECUCION_IDPEJECUCION { get; set; }
        public short ESTADO_SOLUCION_IDESOLUCION { get; set; }
    
        public virtual PROBLEMA_EJECUCION PROBLEMA_EJECUCION { get; set; }
    }
}
