//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREA
    {
        public TAREA()
        {
            this.FLUJO_TAREA = new HashSet<FLUJO_TAREA>();
            this.FUNCIONARIO_TAREA = new HashSet<FUNCIONARIO_TAREA>();
        }
    
        public int IDTAREA { get; set; }
        public string NOMBRETAREA { get; set; }
        public System.DateTime FECHACREACION { get; set; }
        public int ESTADO_TAREA_IDTAREA { get; set; }
    
        public virtual ESTADO_TAREA ESTADO_TAREA { get; set; }
        public virtual ICollection<FLUJO_TAREA> FLUJO_TAREA { get; set; }
        public virtual ICollection<FUNCIONARIO_TAREA> FUNCIONARIO_TAREA { get; set; }
    }
}
