//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_FUNCIONARIO
    {
        public USUARIO_FUNCIONARIO()
        {
            this.ROL = new HashSet<ROL>();
        }
    
        public short IDUFUNCIONARIO { get; set; }
        public short FUNCIONARIO_IDFUNCIONARIO { get; set; }
        public decimal USUARIO_USUARIO_ID { get; set; }
    
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
        public virtual ICollection<ROL> ROL { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
