//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.USUARIO_FUNCIONARIO = new HashSet<USUARIO_FUNCIONARIO>();
        }
    
        public decimal USUARIO_ID { get; set; }
        public string NOMBREUSUARIO { get; set; }
        public string CONTRASEÑA { get; set; }
    
        public virtual ICollection<USUARIO_FUNCIONARIO> USUARIO_FUNCIONARIO { get; set; }
    }
}
